[package]
name = "libsql_migration"
version = "0.1.0"
edition = "2024"

[dependencies]
libsql = "0.9.4"

[dev-dependencies]
tempfile = "3.10"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
